openapi: 3.0.0
info:
  title: Fruitables API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.1
servers:
  - url: http://localhost:8000/api/v1
    description: Local Server
  - url: http://example.com
    description: Live Server
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []
paths:
  /users/register:
    post:
      tags:
        - Users
      summary: Registration of user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          multipart/form-data:
              schema: 
                type: object
                properties:
                  name: 
                    type: string
                  email: 
                    type: string
                  password: 
                    type: string
                  role: 
                    type: string
                  googleId: 
                    type: string
                  avatar:
                    type: string
                    format: binary
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/login:
    post:
      tags:
        - Users
      summary: Login of user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
              schema: 
                type: object
                properties:
                  email: 
                    type: string
                  password: 
                    type: string
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/generateNewTokens:
    post:
      tags:
        - Users
      summary: Login of user.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /users/googleLogin:
    post:
      tags:
        - Users
      summary: Login with Google (Use durectly in browser URL).
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /categories/list-categories:
    get:
      tags:
        - Categories
      summary: Gives list of Categories.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: The number of items to skip before starting to collect the result set
        - in: query
          name: pageSize
          schema:
            type: integer
          description: The numbers of items to return
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /categories/update-category/{category_id}:
    put:
      tags:
        - Categories
      summary: Update category.
      parameters:
        - in: path
          name: category_id
          schema:
            type: string
          description: The number of items to skip before starting to collect the result set
      requestBody:
        content:
          application/json:
              schema: 
                type: object
                properties:
                  name: 
                    type: string
                  description: 
                    type: string
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string